version: '3'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    restart: unless-stopped
  
  cli:
    build:
      context: ..
      dockerfile: docker/Dockerfile.cli
    volumes:
      - ../:/app
      - ${PWD}:/data
    # This is a placeholder command that will be overridden when running the container
    command: ["--help"]

  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    volumes:
      - ../:/app 